### PR TITLE
add community cleaning and conversion to presence-absence in R

### PR DESCRIPTION
**Pull request by evalieungh**
Hi @jogaudard  and @RagnhildGya! I made a simple script to clean up the raw community data a bit. It converts it to presence-absence, but that can be avoided by skipping the last mutate line. Also adding a new column with a unique subplot ID by combining site, block, plot, and subplot.
Might be useful for others too! 
There are probably more things that need to be checked and changed, but this is a start.

### CODE REVIEW

**Comment by evalieungh** [comment]
Added some weather data (maybe not necessary) and a script for plotting OTC effetcs.

**Comment by jogaudard** [comment]
Hey
I see you are committing to master. Are those scripts completely finished and ready for publishing?
Also, the csv file with data should go on OSF. I think it is better practice to separate the scripts and the data.

**Comment by evalieungh** [comment]
I'm not sure if it should be part of any publication, but I don't think I will work further on these for quite some time. Should they rather go to another branch?

**Comment by RagnhildGya** [comment]
You know, I actually worked on the code for making the OTC plots and stuff yesterday. So I think me and Joseph can figure something out either based on the new branch I made in my repo (that I can push to this version if we want), or we merge this one and I add my changes to that branch. But med and Joseph can figure it out when he is back from the field. Thanks for the help anyway Eva :)

**Comment by jogaudard** [comment]
Ok then if it is in almost finished state master is probably the right branch ;-)
But still, those data should go to OSF and not github. It is too big and not the way we do things.

**Pull request closed without merging**
